
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'

    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise (2a22bfca-1d56-46ef-9b7a-0a93d5552606)'
    subscriptionId: '2a22bfca-1d56-46ef-9b7a-0a93d5552606'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevOpsPipeLineRG'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/moragheb/react-and-spring-data-rest/master/Environemnet%20ARM%20Template/template.json'
    deploymentMode: 'Incremental'


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: 'clean'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    javaHomeOption: 'Path'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    codeCoverageSourceDirectories: src/main    

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Package-build'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Package-build'
  condition: succeededOrFailed()    


- task: Docker@1
  displayName: 'build an image'
  inputs:
    azureSubscriptionEndpoint: 'Visual Studio Enterprise (2a22bfca-1d56-46ef-9b7a-0a93d5552606)'
    azureContainerRegistry: ACRSpringbootimages.azurecr.io
    dockerFile: src/Dockerfile
    imageName: 'Web:$(Build.BuildNumber)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: .

- task: Docker@1
  displayName: 'Push Image'
  inputs:
    azureSubscriptionEndpoint: 'Visual Studio Enterprise (2a22bfca-1d56-46ef-9b7a-0a93d5552606)'
    azureContainerRegistry: ACRSpringbootimages.azurecr.io
    command: 'Push an image'
    imageName: 'Web:$(Build.BuildNumber)'