version: '3.4'
services:
  reactandspringdatarest-frontend:
    image: reactandspringdatarest-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: https://localhost:8080/
    ports:
      - 3000:3000
  reactandspringdatarest-backend:
    image: reactandspringdatarest-backend:latest
    ports:
      - 8080:8080


