apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: .\Kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: reactandspringdatarest
  name: reactandspringdatarest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reactandspringdatarest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: .\Kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: reactandspringdatarest
    spec:
      containers:
      - image: reactandspringdatarest
        imagePullPolicy: ""
        name: reactandspringdatarest
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
